import * as React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { ITab } from "../types/ITab";
import { TweetList } from "../components/home/TweetList";
import { CreateTweetBox } from "../components/home/CreateTweetBox";

const Home: NextPage = () => {
  const [tab, setTab] = React.useState<ITab>(ITab.ForYou);

  return (
    <>
      <Head>
        <title>Home / Twixer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <header className="">
          <h4 className="p-3 text-2xl font-semibold text-black dark:text-white">
            Home
          </h4>

          <div className="mt-3 flex items-center justify-around border-b ">
            {(Object.keys(ITab) as (keyof typeof ITab)[]).map((key) => {
              const isSelected = tab === ITab[key];

              return (
                <button
                  key={key}
                  className={`mb-1 flex flex-1 items-center justify-center space-x-2 py-2 px-1 hover:bg-black/10 `}
                  onClick={() => setTab(ITab[key])}
                >
                  <span
                    className={`border-b-4 px-2 opacity-40 dark:text-white ${
                      isSelected
                        ? " scale-105 border-blue-400 opacity-100"
                        : "border-transparent"
                    } text-sm font-semibold text-gray-600 transition-all duration-200 ease-in-out `}
                  >
                    {ITab[key]}
                  </span>
                </button>
              );
            })}
          </div>
        </header>

        <CreateTweetBox />

        <TweetList tab={tab} />
      </main>
    </>
  );
};

export default Home;
