import type { NextPage } from "next";
import Head from "next/head";

const NotificationPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Notifications</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        notification
      </main>
    </>
  );
};

export default NotificationPage;
